### ISSUE TITLE
Mid point for an unbounded interval

### ISSUE THREAD

**Issue by lbenet** [oheim/ITF1788#10]
According to the standard, the mid point of unbounded intervals, as well as for empty intervals, should return no value at level 1; cf. table 10.2, in page 39 of the standard. Yet, at level 2, a value can be fixed, for instance for entire intervals. 

The question is why (in the ITF1788) test suite `mid(Interval(0,Inf)` the largest finite floating point?

See https://github.com/JuliaIntervals/IntervalArithmetic.jl/issues/107

cc @dpsanders

**Comment by oheim** [comment]
It is defined in Section 12.12.8 of the standard.

Also in the simplified version IEEE 1788.1, you can find the same definition in Section 6.7.6 (http://grouper.ieee.org/groups/1788/email/msg09048.html).
